development:
  adapter: postgresql
  encoding: unicode
  database: ziq_development
  pool: 5
  host: localhost
  username: ideesbebe
  password: sefsef

test:
  adapter: postgresql
  encoding: unicode
  database: ziq_test
  host: localhost
  pool: 5
  username: ideesbebe
  password: sefsef

production:
  adapter: postgresql
  encoding: unicode
  database: ziq_production
  host: localhost
  pool: 5
  username: ideesbebe
  password: sefsef
